# Configuración - Sitio
title: 			Ramsés Leal
user: 			R12Leal | Ramsès Leal
logo:       /img/icon/r12leal_logo.png
header-img: 	img/backgrounds/header-background-mini.jpg
email: 			leal.ramses@gmail.com
description: 	"Ramsés Leal - CV & Blog"
baseurl: 		""
url: 			"https://r12leal.me"

# Social Networks
tw: R12Leal
lk: ramsesll
gh: R12Leal
gg: RamsésLeal
yt: UCEXlUn3iNv6AfG41lO7pzQw

# Configuración - Plataforma
gga: 			    UA-91164988-1 # Google Analytics user
markdown: 		kramdown
highlighter: 	rouge
permalink: /:year/:title/
paginate: 		5
exclude: 		["less","node_modules","Gruntfile.js","package.json","README.md"]

# Gems
gems: [jekyll-paginate]
